#
# ~/.bashrc
# by anejL

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'

PS1="\[$(tput setaf 4)\][ \[$(tput sgr0)\]\u@\h \[$(tput setaf 2)\]\w \[$(tput setaf 4)\]] $ \[$(tput sgr0)\]"
#PATH=$PATH:/home/anej/.config/nvim/bundle/vim-live-latex-preview/bin/
#PATH=$PATH:~/.vim/bundle/vim-live-latex-preview/bin

SCRIPTDIR="$HOME/Documents/Scripts"

export EDITOR=nvim

alias cv='cd $HOME/Documents/Latex/CV && vim cv.tex'
alias hkd='vim $HOME/.config/sxhkd/sxhkdrc && sxhkd'

alias o='cd /opt'
alias odw='cd /opt/dwm'
alias ost='cd /opt/st'

alias vc='vim config.h'
alias vcc='vim config.h && sudo make clean install'

alias psyu='sudo pacman -Syu'
alias psyyu='sudo pacman -Syyu'
alias ps='sudo pacman -S'

alias vim='nvim'
alias ds='cd $SCRIPTDIR'
alias dsd='cd $SCRIPTDIR/dwmbar' 
alias dsa='cd $SCRIPTDIR/archer'

alias mt='$SCRIPTDIR/mount.sh'

alias aura='$SCRIPTDIR/aura/aura.sh'
alias gc='$SCRIPTDIR/gitpush.sh'

alias brc='vim $HOME/.bashrc && source $HOME/.bashrc'
